### ISSUE TITLE
PersonRestService has no GetMapping

### ISSUE THREAD

**Issue by eacarvalho** [FelipeAdorno/specification-sample#1]
Felipe, I think you forgot to annotate the method "list" on the "PersonRestService" as @GetMapping.  If you don't have the method annotation you don't have any Rest Mapping for GET verb.

Interface:
org.springframework.web.bind.annotation.GetMapping

See you.

**Comment by FelipeAdorno** [comment]
@eacarvalho I forgot, thanks for remember me.
